### ISSUE TITLE
invalid syntax - maybe python3 incompatible ?

### ISSUE THREAD

**Issue by devZer0** [Stratoscale/dim#2]
i'm getting this after install
```
# dim-display
Traceback (most recent call last):
  File "/usr/local/bin/dim-display", line 6, in <module>
    from dim.display import main
  File "/usr/local/lib/python3.6/site-packages/dim/display.py", line 12
    'age': lambda (image, age): age,
                  ^
SyntaxError: invalid syntax
```

**Comment by IliaFeldgun** [comment]
Yes, only python2 is supported currently.
